
## 数组
### 1. 多维数组
- 一个ndarray是一个通用发多维同类数据容器，它可以是一维的，可以使二维的，可以是三维的，也可以滴更高维的。
- 构成数组的元素是同质的，数组送的每一个只都具有相同的数据

### 2. 数组创建
- 如果想函数传入一个类表或者元组，讲构造简单的一个数组
#### 一维数组
        
        # 导入模块，并重命名为np
        import numpy ads np
        
        arr1 = np.array([1,2,3,4,5,6,7])
        print("一维数组arr1：",arr)
        
        arr2 = np.array([1,2,3,4,5,6,7,87,'a'])
        print("一维数组arr2:{0}".format(arr2))
        
        
#### 二维数组

        arr2 = np.array([
                    [1,2,3,4,5],
                    [11,12,13,14,15],
                    [21,22,23,24,25],
                    [31,32,33,34,35]])
        print()


### 3. 数组生产函数
 1. array：将输入转换成为ndarray，但如果输入已经是ndarray则不再复制
 2. arange：Python内件函数range的数组版，返回一个数组
 3. ones：根据指定的形状和数据类型生成全都是1的数组
 4. ones_like：根据所给的数据生成一个一模一样的全都是1的数组
 5. zero：根据指定的形状和数据类型生成全都是0的数组
 6. zero_like：根据所给的数据生成一个一模一样的全都是0的数组
 7. empty：根据指定的形状和数据类型生成一个没有初始值的空数组
 8. empty_like：根据所给的数据生成一个一模一样但是没有初始值的空数组
 9. full：根据指定的形状和数据类型生成指定数值的数组
 10. full_like：根据所给的数据生成一个一模一样但是指定数值的数组
 11. eye.identity：生成一个特征矩形，对角线全是1，其他都是0
 
 
### 4. 数组访问
#### 位置索引
 - 可以通过正向索引、负向索引、切片索引和无限索引获取元素，在一维数组中，类表的所有索引方法都可以用在数组上
#### 神奇索引
- 一维数组中，可以将任意位置的索引组装为列表，用作对元素的或暗区，称之为神奇索引，它一其他的切片不同，它总是将数据复制到一个新的数组中。
- **在二维数组中，位置索引必须写成"[rows,cols]"的形式，某一列或某一行的所有元素，用“ ：”代替**
### 数组不规则访问
- 如果要取二维数组的某几行，某几列，应该适应ix_()函数

        # 第一行、第三行、最后一行，第二列、第三列、最后一列
        print(arr2[np.ix_([0,2,-1],[1,2,-1])])
### 5. 四则运算
- 在numpy模块中，它允许对数组进行批量操作而无需任何for循环，这一操作也叫作向量化
- 任何两个尺寸相同的数组之间，都可以进行批量操作，不同尺寸的数组之间的曹锁，则需要用到广播特性
- 实现……

### 6. 常用数学函数
- np.e： 常熟e    
-    
        
   

#### 一维列表

In [5]:
import numpy as np

data = [1, 2, 3, 4, 5, 6]
myarray1 = np.array(data)
print(myarray1)

print(type(data))
print(type(myarray1))

[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


#### 二维列表

In [4]:
data2 = ([[11,12,13,14,15],
          [21,22,23,24,25],
          [31,32,33,34,35],
          [41,42,43,44,45]])
myarray2 = np.array(data2)
print(myarray2)
print(type(data2))
print(type(myarray2))

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
<class 'list'>
<class 'numpy.ndarray'>


#### 三维列表

In [7]:
data3 = [[[1, 2, 3],[4, 5, 6],[7, 8, 9]],
         [[11, 12, 13],[14, 15, 16],[17, 18, 19]],
         [[21, 22, 23],[24, 25, 26],[27, 28, 29]]]
myarray3 = np.array(data3)
print(myarray3)
print(type(data3))
print(type(myarray3))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
<class 'list'>
<class 'numpy.ndarray'>


In [10]:
# 乘法运算
print(myarray3 * 2)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [14]:
print(np.where(myarray3>60, 90, 0))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [1]:
import numpy as np
myarray4 = np.ones(3, 3)

TypeError: data type not understood